name: Test Miaomiaowu Feed (ImmortalWrt 25.05)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone ImmortalWrt 25.05
        run: |
          git clone --depth=1 -b openwrt-25.05 https://github.com/immortalwrt/immortalwrt.git
          cd immortalwrt

          echo "src-git miaomiaowu https://github.com/xiaohai77/OpenWrt-MMW.git;main" >> feeds.conf.default

          ./scripts/feeds update miaomiaowu
          ./scripts/feeds install -a -p miaomiaowu

          find package/feeds

          test -d package/feeds/miaomiaowu/luci-app-miaomiaowu
          test -d package/feeds/miaomiaowu/miaomiaowu

          echo "PASS"
