name: Test Miaomiaowu Feed

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone OpenWrt
        run: |
          git clone --depth=1 https://github.com/openwrt/openwrt.git
          cd openwrt

      - name: Add Feed
        run: |
          cd openwrt

          echo "src-git miaomiaowu https://github.com/xiaohai77/OpenWrt-MMW.git;main" >> feeds.conf.default

      - name: Update Feed
        run: |
          cd openwrt

          ./scripts/feeds update miaomiaowu

      - name: Install Feed
        run: |
          cd openwrt

          ./scripts/feeds install -a -p miaomiaowu

      - name: Verify
        run: |
          cd openwrt

          echo "===== package/feeds ====="
          find package/feeds

          test -d package/feeds/miaomiaowu/luci-app-miaomiaowu
          test -d package/feeds/miaomiaowu/miaomiaowu

          echo "PASS"
